import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  container: { flex: 1, backgroundColor: colors.background, paddingHorizontal: 24, paddingTop: 64 },
  darkContainer: { backgroundColor: '#120D10' },
  darkText: { color: '#FFF7F8' },
  darkMuted: { color: '#E3C4C8' },
  darkGlass: { backgroundColor: 'rgba(52, 38, 42, 0.92)', borderColor: 'rgba(255, 255, 255, 0.18)' },
  darkInput: { backgroundColor: 'rgba(58, 42, 47, 0.96)', borderColor: 'rgba(255, 255, 255, 0.2)' },
  darkInputText: { color: '#FFF7F8' },
  darkTimePanel: { backgroundColor: 'rgba(58, 42, 47, 0.98)', borderColor: 'rgba(255, 255, 255, 0.22)' },
  darkOptionPill: { backgroundColor: 'rgba(58, 42, 47, 0.94)', borderColor: 'rgba(255, 255, 255, 0.22)' },
  darkWashTop: { backgroundColor: 'rgba(107, 29, 47, 0.24)' },
  darkWashBottom: { backgroundColor: 'rgba(245, 230, 232, 0.04)' },
  backgroundWashTop: { backgroundColor: 'rgba(245, 230, 232, 0.86)', borderBottomRightRadius: 160, height: 260, left: -100, position: 'absolute', top: -90, transform: [{ rotate: '-12deg' }], width: '95%' },
  backgroundWashBottom: { backgroundColor: 'rgba(107, 29, 47, 0.06)', borderTopLeftRadius: 180, bottom: -120, height: 260, position: 'absolute', right: -90, transform: [{ rotate: '12deg' }], width: '90%' },
  loginContent: { flex: 1, justifyContent: 'flex-start', marginTop: 12, paddingTop: 16 },
  loginScroll: { flexGrow: 1, paddingBottom: 18 },
  loginTopBar: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  homeBrandWrap: { alignItems: 'center', flexDirection: 'row', gap: 8, marginBottom: 7 },
  liveBadge: { alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.42)', borderColor: 'rgba(255, 255, 255, 0.8)', borderRadius: 15, borderWidth: 1, flexDirection: 'row', paddingHorizontal: 11, paddingVertical: 8 },
  liveDot: { backgroundColor: '#9C5263', borderRadius: 4, height: 7, marginRight: 7, width: 7 },
  liveBadgeText: { color: colors.burgundy, fontSize: 9, fontWeight: '800', letterSpacing: 1.1 },
  loginHeroCopy: { marginTop: 46 },
  eyebrow: { color: colors.burgundy, fontSize: 11, fontWeight: '800', letterSpacing: 1.5, marginBottom: 12 },
  title: { color: colors.ink, fontSize: 38, fontWeight: '800', letterSpacing: -0.8, lineHeight: 43 },
  subtitle: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: 14, maxWidth: 260 },
  loginPanelWrap: { marginTop: 32, position: 'relative' },
  loginPanelDepth: { backgroundColor: 'rgba(107, 29, 47, 0.13)', borderRadius: 25, bottom: -8, left: 8, position: 'absolute', right: -8, top: 8 },
  loginPanel: { backgroundColor: 'rgba(255, 255, 255, 0.34)', borderColor: 'rgba(255, 255, 255, 0.88)', borderRadius: 26, borderWidth: 1, elevation: 5, overflow: 'hidden', padding: 18, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 16 },
  form: { gap: 12 },
  inputCard: { backgroundColor: colors.glassStrong, borderColor: 'rgba(255, 255, 255, 0.9)', borderRadius: 16, borderWidth: 1, elevation: 3, overflow: 'hidden', paddingHorizontal: 16, paddingTop: 13, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 12 },
  inputLabel: { color: colors.burgundy, fontSize: 10, fontWeight: '800', letterSpacing: 1.2 },
  input: { color: colors.ink, fontSize: 16, height: 38, padding: 0 },
  primaryButton: { alignItems: 'center', backgroundColor: colors.burgundy, borderColor: 'rgba(255, 255, 255, 0.35)', borderRadius: 16, borderWidth: 1, elevation: 8, flexDirection: 'row', height: 58, justifyContent: 'center', marginTop: 24, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.25, shadowRadius: 14 },
  primaryButtonText: { color: colors.white, fontSize: 16, fontWeight: '800' },
  buttonArrow: { color: colors.white, fontSize: 22, marginLeft: 12, marginTop: -2 },
  signupButton: { alignItems: 'center', flexDirection: 'row', justifyContent: 'center', marginTop: 18, paddingVertical: 8 },
  signupPrompt: { color: colors.muted, fontSize: 13 },
  signupLink: { color: colors.burgundy, fontSize: 13, fontWeight: '800', marginLeft: 5 },
  loginFooter: { alignItems: 'center', justifyContent: 'flex-end', paddingBottom: 28 },
  appName: { color: colors.burgundy, fontSize: 18, fontWeight: '800', letterSpacing: 0.3 },
  appTagline: { color: colors.muted, fontSize: 11, marginTop: 4 },
  copyright: { color: colors.muted, fontSize: 10, marginTop: 10 },
  profileHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  backButton: { alignItems: 'center', backgroundColor: colors.glassStrong, borderColor: 'rgba(255, 255, 255, 0.9)', borderRadius: 22, borderWidth: 1, elevation: 3, height: 44, justifyContent: 'center', shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.08, shadowRadius: 8, width: 44 },
  backArrow: { color: colors.burgundy, fontSize: 32, fontWeight: '300', lineHeight: 34, marginTop: -3 },
  profileHeaderTitle: { color: colors.ink, fontSize: 18, fontWeight: '800' },
  editProfileButton: { backgroundColor: colors.glassStrong, borderColor: 'rgba(255, 255, 255, 0.9)', borderRadius: 14, borderWidth: 1, paddingHorizontal: 13, paddingVertical: 8 },
  editProfileText: { color: colors.burgundy, fontSize: 12, fontWeight: '800' },
  profileScroll: { paddingBottom: 40 },
  profileHeroWrap: { marginTop: 30, position: 'relative' },
  profileHeroDepth: { backgroundColor: 'rgba(107, 29, 47, 0.15)', borderRadius: 24, bottom: -8, left: 8, position: 'absolute', right: -8, top: 8 },
  profileHero: { alignItems: 'center', backgroundColor: colors.glassStrong, borderColor: 'rgba(255, 255, 255, 0.9)', borderRadius: 24, borderWidth: 1, elevation: 5, overflow: 'hidden', paddingBottom: 24, paddingTop: 26, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.1, shadowRadius: 16 },
  avatarLarge: { alignItems: 'center', backgroundColor: colors.burgundy, borderColor: 'rgba(255, 255, 255, 0.6)', borderRadius: 42, borderWidth: 3, elevation: 8, height: 84, justifyContent: 'center', shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 7 }, shadowOpacity: 0.25, shadowRadius: 12, width: 84 },
  avatarText: { color: colors.white, fontSize: 32, fontWeight: '800' },
  profileName: { color: colors.ink, fontSize: 24, fontWeight: '800', marginTop: 16 },
  profileEmail: { color: colors.muted, fontSize: 14, marginTop: 5 },
  memberBadge: { backgroundColor: colors.blush, borderColor: 'rgba(107, 29, 47, 0.08)', borderRadius: 14, borderWidth: 1, marginTop: 16, paddingHorizontal: 12, paddingVertical: 7 },
  memberBadgeText: { color: colors.burgundy, fontSize: 10, fontWeight: '800', letterSpacing: 1.1 },
  statsRow: { flexDirection: 'row', gap: 10, marginTop: 18 },
  statCard: { alignItems: 'center', backgroundColor: colors.glass, borderColor: 'rgba(255, 255, 255, 0.85)', borderRadius: 17, borderWidth: 1, elevation: 3, flex: 1, overflow: 'hidden', paddingVertical: 15, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 10 },
  statValue: { color: colors.burgundy, fontSize: 19, fontWeight: '800' },
  statLabel: { color: colors.muted, fontSize: 9, fontWeight: '800', letterSpacing: 1.1, marginTop: 5 },
  profileSectionTitle: { color: colors.ink, fontSize: 12, fontWeight: '800', letterSpacing: 1.4, marginBottom: 12, marginTop: 30 },
  preferencePanel: { backgroundColor: colors.glass, borderColor: 'rgba(255, 255, 255, 0.86)', borderRadius: 20, borderWidth: 1, elevation: 3, paddingHorizontal: 16, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 12 },
  preferenceRow: { alignItems: 'center', flexDirection: 'row', minHeight: 74 },
  preferenceIcon: { alignItems: 'center', backgroundColor: colors.blush, borderRadius: 12, height: 36, justifyContent: 'center', marginRight: 12, width: 36 },
  preferenceIconText: { color: colors.burgundy, fontSize: 17, fontWeight: '700' },
  preferenceCopy: { flex: 1 },
  preferenceTitle: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  preferenceDetail: { color: colors.muted, fontSize: 11, marginTop: 4 },
  settingToggle: { backgroundColor: 'rgba(107, 29, 47, 0.12)', borderColor: 'rgba(255, 255, 255, 0.75)', borderRadius: 12, borderWidth: 1, height: 24, justifyContent: 'center', paddingHorizontal: 3, width: 42 },
  settingToggleActive: { backgroundColor: colors.burgundy },
  settingKnob: { backgroundColor: colors.white, borderRadius: 8, height: 16, width: 16 },
  settingKnobActive: { alignSelf: 'flex-end' },
  preferenceDivider: { backgroundColor: colors.line, height: 1, marginLeft: 48 },
  logoutButton: { alignItems: 'center', borderColor: colors.line, borderRadius: 15, borderWidth: 1, flexDirection: 'row', height: 52, justifyContent: 'center', marginTop: 24 },
  logoutText: { color: colors.burgundy, fontSize: 15, fontWeight: '800' },
  logoutArrow: { color: colors.burgundy, fontSize: 20, marginLeft: 10 },
  dashboardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  homeBrand: { color: colors.burgundy, fontSize: 12, fontWeight: '800', letterSpacing: 1.4 },
  dashboardTitle: { color: colors.ink, fontSize: 34, fontWeight: '800', letterSpacing: -0.6 },
  profileButton: { alignItems: 'center', backgroundColor: colors.glassStrong, borderColor: 'rgba(255, 255, 255, 0.9)', borderRadius: 22, borderWidth: 1, elevation: 3, height: 44, justifyContent: 'center', shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.08, shadowRadius: 8, width: 44 },
  profileInitial: { color: colors.burgundy, fontSize: 16, fontWeight: '800', textAlign: 'center', lineHeight: 22, includeFontPadding: false },
  progressCard: { alignItems: 'center', backgroundColor: colors.glassStrong, borderColor: 'rgba(255, 255, 255, 0.9)', borderRadius: 20, borderWidth: 1, elevation: 4, flexDirection: 'row', justifyContent: 'space-between', marginTop: 30, overflow: 'hidden', paddingHorizontal: 20, paddingVertical: 20, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.08, shadowRadius: 14 },
  progressCopy: { flex: 1 },
  progressLabel: { color: colors.burgundy, fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginBottom: 8 },
  progressValue: { color: colors.ink, fontSize: 18, fontWeight: '700' },
  progressHint: { color: colors.muted, fontSize: 12, marginTop: 7 },
  progressRing: { alignItems: 'center', borderColor: colors.burgundy, borderRadius: 32, borderWidth: 4, height: 64, justifyContent: 'center', width: 64 },
  progressPercent: { color: colors.burgundy, fontSize: 14, fontWeight: '800' },
  dashboardScroll: { paddingBottom: 36 },
  searchCard: { alignItems: 'center', backgroundColor: colors.glass, borderColor: 'rgba(255, 255, 255, 0.86)', borderRadius: 16, borderWidth: 1, flexDirection: 'row', marginTop: 18, overflow: 'hidden', paddingHorizontal: 14, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.05, shadowRadius: 10 },
  searchIcon: { color: colors.burgundy, fontSize: 24, marginRight: 9, marginTop: -3 },
  searchInput: { color: colors.ink, flex: 1, fontSize: 14, height: 48 },
  filterHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 28 },
  sectionTitle: { color: colors.ink, fontSize: 12, fontWeight: '800', letterSpacing: 1.4 },
  addTaskButton: { alignItems: 'center', backgroundColor: colors.burgundy, borderRadius: 15, flexDirection: 'row', paddingHorizontal: 12, paddingVertical: 8 },
  addTaskPlus: { color: colors.white, fontSize: 18, fontWeight: '400', lineHeight: 18, marginRight: 5 },
  addTaskText: { color: colors.white, fontSize: 12, fontWeight: '800' },
  filterRow: { flexDirection: 'row', gap: 8, marginTop: 30 },
  filterPill: { borderRadius: 20, paddingHorizontal: 18, paddingVertical: 10 },
  filterPillActive: { backgroundColor: colors.burgundy, borderColor: 'rgba(255, 255, 255, 0.35)', borderWidth: 1, elevation: 3, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.18, shadowRadius: 7 },
  filterText: { color: colors.muted, fontSize: 14, fontWeight: '700' },
  filterTextActive: { color: colors.white },
  categoryRow: { gap: 8, paddingTop: 14 },
  categoryPill: { backgroundColor: 'rgba(255, 255, 255, 0.34)', borderColor: 'rgba(255, 255, 255, 0.82)', borderRadius: 14, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 8 },
  categoryPillActive: { backgroundColor: colors.blush, borderColor: colors.burgundy },
  categoryText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  categoryTextActive: { color: colors.burgundy },
  clearCompletedButton: { alignSelf: 'flex-end', marginTop: 14, paddingVertical: 4 },
  clearCompletedText: { color: colors.burgundy, fontSize: 12, fontWeight: '700' },
  emptyState: { alignItems: 'center', backgroundColor: colors.glass, borderColor: 'rgba(255, 255, 255, 0.86)', borderRadius: 22, borderWidth: 1, marginTop: 24, paddingHorizontal: 24, paddingVertical: 28, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 12 },
  emptyStateTitle: { color: colors.ink, fontSize: 20, fontWeight: '800' },
  emptyStateText: { color: colors.muted, fontSize: 13, lineHeight: 20, marginTop: 8, textAlign: 'center' },
  taskList: { marginTop: 14 },
  taskRow: { alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.24)', borderColor: 'rgba(255, 255, 255, 0.82)', borderRadius: 20, borderWidth: 1, elevation: 4, flexDirection: 'row', marginBottom: 12, minHeight: 86, overflow: 'hidden', paddingHorizontal: 14, position: 'relative', shadowColor: colors.burgundy, shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.08, shadowRadius: 14 },
  taskRowCompact: { minHeight: 72 },
  taskGlass: { ...StyleSheet.absoluteFill, backgroundColor: colors.glass, borderRadius: 20 },
  taskBody: { alignItems: 'center', flex: 1, flexDirection: 'row', minHeight: 84, paddingVertical: 12 },
  taskBodyCompact: { minHeight: 68 },
  taskDeleteButton: { alignItems: 'center', backgroundColor: 'rgba(245, 230, 232, 0.8)', borderColor: 'rgba(107, 29, 47, 0.14)', borderRadius: 15, borderWidth: 1, height: 32, justifyContent: 'center', marginLeft: 8, width: 32 },
  taskDeleteText: { color: colors.burgundy, fontSize: 22, fontWeight: '300', lineHeight: 22, marginTop: -2 },
  checkbox: { alignItems: 'center', borderColor: colors.burgundy, borderRadius: 12, borderWidth: 1.5, height: 24, justifyContent: 'center', marginRight: 14, width: 24 },
  checkboxDone: { backgroundColor: colors.burgundy },
  checkmark: { color: colors.white, fontSize: 15, fontWeight: '800' },
  taskCopy: { flex: 1 },
  taskTitle: { color: colors.ink, fontSize: 15, fontWeight: '800', marginBottom: 7 },
  taskTitleDone: { color: colors.muted, textDecorationLine: 'line-through' },
  taskMeta: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap' },
  noteIndicator: { color: colors.burgundy, fontSize: 13, fontWeight: '800', marginLeft: 8 },
  priorityDot: { borderRadius: 4, height: 7, marginRight: 6, width: 7 },
  priorityHigh: { backgroundColor: colors.burgundy },
  priorityMedium: { backgroundColor: '#B56B78' },
  priorityLow: { backgroundColor: '#C9A9AE' },
  taskDetail: { color: colors.muted, fontSize: 12 },
  taskBadge: { alignItems: 'center', backgroundColor: colors.blush, borderColor: 'rgba(107, 29, 47, 0.12)', borderRadius: 10, borderWidth: 1, marginTop: 8, paddingHorizontal: 8, paddingVertical: 4 },
  taskBadgeDark: { backgroundColor: 'rgba(255,255,255,0.08)', borderColor: 'rgba(255,255,255,0.18)' },
  taskBadgeText: { color: colors.burgundy, fontSize: 10, fontWeight: '800', letterSpacing: 0.6 },
  taskChevron: { color: colors.muted, fontSize: 26, marginLeft: 12 },
  detailSummary: { flexDirection: 'row', gap: 36, marginTop: 8 },
  detailSummaryItem: { minWidth: 90 },
  detailPriority: { alignItems: 'center', flexDirection: 'row' },
  detailValue: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  secondaryAction: { alignItems: 'center', borderColor: colors.line, borderRadius: 14, borderWidth: 1, height: 48, justifyContent: 'center', marginTop: 12 },
  secondaryActionText: { color: colors.burgundy, fontSize: 14, fontWeight: '800' },
  deleteAction: { alignItems: 'center', height: 42, justifyContent: 'center', marginTop: 4 },
  deleteActionText: { color: '#A04B5D', fontSize: 13, fontWeight: '700' },
  modalBackdrop: { backgroundColor: 'rgba(36, 23, 27, 0.28)', flex: 1, justifyContent: 'flex-end' },
  modalCard: { backgroundColor: 'rgba(255, 255, 255, 0.62)', borderColor: 'rgba(255, 255, 255, 0.92)', borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, elevation: 14, maxHeight: '88%', overflow: 'hidden', paddingHorizontal: 24, paddingTop: 12, paddingBottom: 12, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: -8 }, shadowOpacity: 0.2, shadowRadius: 20 },
  profileEditorCard: { backgroundColor: 'rgba(255, 255, 255, 0.62)', borderColor: 'rgba(255, 255, 255, 0.92)', borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, elevation: 14, overflow: 'hidden', paddingHorizontal: 24, paddingTop: 12, paddingBottom: 30, shadowColor: colors.burgundy, shadowOffset: { width: 0, height: -8 }, shadowOpacity: 0.2, shadowRadius: 20 },
  modalScrollView: { flexGrow: 0, maxHeight: 600 },
  modalScroll: { paddingBottom: 44 },
  modalHandle: { alignSelf: 'center', backgroundColor: 'rgba(107, 29, 47, 0.18)', borderRadius: 3, height: 5, marginBottom: 22, width: 40 },
  modalHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  modalEyebrow: { color: colors.burgundy, fontSize: 10, fontWeight: '800', letterSpacing: 1.4, marginBottom: 7 },
  modalTitle: { color: colors.ink, fontSize: 26, fontWeight: '800' },
  modalClose: { alignItems: 'center', backgroundColor: colors.blush, borderRadius: 18, height: 36, justifyContent: 'center', width: 36 },
  modalCloseText: { color: colors.burgundy, fontSize: 25, fontWeight: '300', lineHeight: 27, marginTop: -2 },
  profilePhotoPicker: { alignItems: 'center', marginTop: 24 },
  avatarEdit: { alignItems: 'center', borderColor: 'rgba(255, 255, 255, 0.7)', borderRadius: 44, borderWidth: 3, height: 88, justifyContent: 'center', width: 88 },
  avatarEditFallback: { backgroundColor: colors.burgundy },
  photoEditBadge: { alignItems: 'center', backgroundColor: colors.burgundy, borderColor: colors.white, borderRadius: 13, borderWidth: 2, height: 26, justifyContent: 'center', marginLeft: 56, marginTop: -27, width: 26 },
  photoEditBadgeText: { color: colors.white, fontSize: 18, lineHeight: 20 },
  changePhotoText: { color: colors.burgundy, fontSize: 13, fontWeight: '800', marginTop: 13 },
  taskInput: { backgroundColor: 'rgba(255, 255, 255, 0.45)', borderColor: colors.line, borderRadius: 14, borderWidth: 1, color: colors.ink, fontSize: 15, height: 54, marginTop: 24, paddingHorizontal: 15 },
  notesInput: { height: 92, paddingTop: 14 },
  timeSelect: { alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.42)', borderColor: 'rgba(255, 255, 255, 0.86)', borderRadius: 14, borderWidth: 1, flexDirection: 'row', marginTop: 10, minHeight: 58, paddingHorizontal: 14 },
  clockIcon: { color: colors.burgundy, fontSize: 24, marginRight: 12 },
  timeSelectCopy: { flex: 1 },
  timeSelectLabel: { color: colors.muted, fontSize: 9, fontWeight: '800', letterSpacing: 1.2, marginBottom: 3 },
  timeSelectValue: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  timeSelectArrow: { color: colors.burgundy, fontSize: 22 },
  nativeTimePanel: { alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.9)', borderColor: 'rgba(107, 29, 47, 0.18)', borderRadius: 16, borderWidth: 1, marginTop: 10, overflow: 'hidden', paddingTop: 10 },
  nativeTimeHint: { color: colors.burgundy, fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginBottom: 2 },
  modalLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.3, marginBottom: 10, marginTop: 22 },
  optionRow: { flexDirection: 'row', gap: 8 },
  optionPill: { alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.38)', borderColor: 'rgba(255, 255, 255, 0.82)', borderRadius: 15, borderWidth: 1, flexDirection: 'row', paddingHorizontal: 12, paddingVertical: 9 },
  optionPillActive: { backgroundColor: colors.blush, borderColor: colors.burgundy },
  optionText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  optionTextActive: { color: colors.burgundy },
  modalButton: { marginTop: 28 },
  primaryButtonDisabled: { opacity: 0.45 },
  // Premium UI Additions
  toastContainer: { position: 'absolute', bottom: 30, left: 24, right: 24, backgroundColor: colors.ink, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.3, shadowRadius: 12, elevation: 10, zIndex: 999 },
  toastText: { color: '#FFF7F8', fontSize: 14, fontWeight: '600' },
  toastButton: { backgroundColor: colors.burgundy, paddingVertical: 8, paddingHorizontal: 16, borderRadius: 10 },
  toastButtonText: { color: colors.white, fontSize: 13, fontWeight: '800' },
  taskBadgeUrgent: { backgroundColor: 'rgba(208, 50, 50, 0.12)', borderColor: 'rgba(208, 50, 50, 0.3)' },
  taskBadgeUrgentText: { color: '#D03232' },
  // Dark Mode clarity fixes
  darkLogoutButton: { backgroundColor: 'rgba(255, 255, 255, 0.06)', borderColor: 'rgba(255, 255, 255, 0.15)' },
  darkSecondaryAction: { backgroundColor: 'rgba(255, 255, 255, 0.06)', borderColor: 'rgba(255, 255, 255, 0.15)' }
});